# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
